#!/usr/bin/env python3
"""Notebook 04 (English) - Target Tracking of Maneuvering Targets (Blair, part 3)."""
from _nbutil import md, code, write_notebook

cells = [
    md(
        "# 04 · Tracking Maneuvering Targets: NCV/NCA, IMM and EKF",
        "**Based on:** *Estimation in Information Fusion* — W. Dale Blair, FUSION Boot Camp 2026, part 3.",
        "",
        "In notebook 03 we built a Kalman filter with a **single** motion model (NCV). Real targets **maneuver**, ",
        "raising three issues: model selection (NCV vs NCA), process-noise tuning, and combining several models (IMM). ",
        "In addition, real measurements (range/bearing) are **nonlinear** → EKF.",
    ),
    md(
        "## A. NCV vs NCA",
        "* **NCV** (Nearly Constant Velocity): state $[p,\\dot p]$. Simple; excellent for straight-line motion; **lags in a maneuver**.",
        "* **NCA** (Nearly Constant Acceleration): state $[p,\\dot p,\\ddot p]$. Tracks acceleration; but 'noisier' in quiet motion (estimates acceleration from noise).",
        "",
        "NCA matrices (DWNA):",
        "$$F=\\begin{bmatrix}1&T&T^2/2\\\\0&1&T\\\\0&0&1\\end{bmatrix},\\; H=\\begin{bmatrix}1&0&0\\end{bmatrix},\\;",
        "Q=\\sigma_a^2\\,\\Gamma\\Gamma^T,\\; \\Gamma=\\begin{bmatrix}T^2/2\\\\T\\\\1\\end{bmatrix}$$",
        "",
        "**The dilemma (from the slides):** small $\\sigma_a$ → small errors in quiet motion but a large lag in a maneuver; ",
        "large $\\sigma_a$ → minimizes the maximum error in a maneuver but increases the average error. **There is no single optimal choice** — the motivation for IMM.",
    ),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "rng = np.random.default_rng(11)",
        "",
        "def ncv(T, sa):",
        "    F=np.array([[1,T],[0,1.]]); H=np.array([[1.,0]])",
        "    G=np.array([[T**2/2],[T]]); Q=(G@G.T)*sa**2",
        "    return F,H,Q",
        "def nca(T, sa):",
        "    F=np.array([[1,T,T**2/2],[0,1,T],[0,0,1.]]); H=np.array([[1.,0,0]])",
        "    G=np.array([[T**2/2],[T],[1.]]); Q=(G@G.T)*sa**2",
        "    return F,H,Q",
        "",
        "class KF:",
        "    def __init__(s,F,H,Q,R,x,P): s.F,s.H,s.Q,s.R=map(np.atleast_2d,(F,H,Q,R)); s.x=np.array(x,float).reshape(-1,1); s.P=np.array(P,float)",
        "    def predict(s): s.x=s.F@s.x; s.P=s.F@s.P@s.F.T+s.Q",
        "    def update(s,z):",
        "        S=s.H@s.P@s.H.T+s.R; K=s.P@s.H.T@np.linalg.inv(S)",
        "        y=np.atleast_2d(z).reshape(-1,1)-s.H@s.x",
        "        s.x=s.x+K@y; s.P=(np.eye(s.P.shape[0])-K@s.H)@s.P",
        "        d=float((y.T@np.linalg.inv(S)@y).item())",
        "        L=float(np.exp(-0.5*d)/np.sqrt(np.linalg.det(2*np.pi*S)))",
        "        return L",
        "print('NCV/NCA + KF defined.')",
    ),
    code(
        "# ground-truth trajectory with a maneuver: constant velocity -> accel 40-60s -> constant again",
        "T=1.0; N=100; sw=10.0",
        "t=np.arange(N)*T",
        "acc=np.where((t>=40)&(t<60), 8.0, 0.0)   # acceleration m/s^2 in the maneuver segment",
        "pos=np.zeros(N); vel=np.zeros(N); vel[0]=30",
        "for k in range(1,N):",
        "    vel[k]=vel[k-1]+acc[k-1]*T",
        "    pos[k]=pos[k-1]+vel[k-1]*T+0.5*acc[k-1]*T**2",
        "meas=pos+sw*rng.standard_normal(N)",
        "",
        "def run_single(make, sa, dim):",
        "    F,H,Q=make(T,sa); P0=np.diag([sw**2,100,100][:dim])",
        "    x0=[meas[0]]+[0]*(dim-1)",
        "    kf=KF(F,H,Q,sw**2,x0,P0); est=[]",
        "    for z in meas: kf.predict(); kf.update(z); est.append(kf.x[0,0])",
        "    return np.array(est)",
        "",
        "est_ncv_lo=run_single(ncv,0.5,2)",
        "est_ncv_hi=run_single(ncv,8.0,2)",
        "est_nca   =run_single(nca,8.0,3)",
        "for name,e in [('NCV sigma_a=0.5',est_ncv_lo),('NCV sigma_a=8',est_ncv_hi),('NCA sigma_a=8',est_nca)]:",
        "    print(f'{name:16s} RMSE={np.sqrt(np.mean((e-pos)**2)):6.2f} m   '",
        "          f'maneuver RMSE={np.sqrt(np.mean((e[40:60]-pos[40:60])**2)):6.2f} m')",
    ),
    md(
        "The result illustrates the dilemma: NCV with small $\\sigma_a$ is excellent overall but poor in the maneuver; ",
        "increasing $\\sigma_a$ or switching to NCA improves the maneuver at the cost of noise in quiet motion.",
    ),
    md(
        "## B. The IMM (Interacting Multiple Model) estimator",
        "The IMM runs **several filters in parallel** (e.g. a quiet NCV + a maneuvering NCV/NCA) and blends them by a ",
        "**model probability** that is updated from each model's likelihood. The IMM cycle (per the 'IMM Algorithm with Two Models' slide):",
        "1. **Interaction/Mixing** — mix the model estimates using the transition matrix $\\pi_{ij}$ and probabilities $\\mu$.",
        "2. **Filtering** — each model performs predict+update from the mixed estimate, computing a likelihood $\\Lambda_j$.",
        "3. **Model Probability Update** — $\\mu_j \\propto \\Lambda_j\\sum_i\\pi_{ij}\\mu_i$.",
        "4. **Combination** — output estimate = weighting of the estimates by the probabilities $\\mu_j$.",
        "",
        "The key (from the slide): *\"the key to successful fusion is increasing the filter standard deviation during the maneuver\"* — which is exactly what IMM does automatically.",
    ),
    code(
        "class IMM:",
        "    \"\"\"IMM with several filters of equal state dimension.\"\"\"",
        "    def __init__(self, filters, Pi, mu):",
        "        self.f=filters; self.Pi=np.array(Pi,float); self.mu=np.array(mu,float)",
        "    def step(self, z):",
        "        r=len(self.f)",
        "        cbar=self.Pi.T@self.mu                      # predicted model probabilities",
        "        mix=(self.Pi*self.mu[:,None])/cbar[None,:]  # mu_{i|j}",
        "        xs=[f.x.copy() for f in self.f]; Ps=[f.P.copy() for f in self.f]",
        "        # mixing",
        "        for j in range(r):",
        "            x0=sum(mix[i,j]*xs[i] for i in range(r))",
        "            P0=sum(mix[i,j]*(Ps[i]+(xs[i]-x0)@(xs[i]-x0).T) for i in range(r))",
        "            self.f[j].x=x0; self.f[j].P=P0",
        "        # filtering + likelihood",
        "        L=np.zeros(r)",
        "        for j in range(r):",
        "            self.f[j].predict(); L[j]=self.f[j].update(z)",
        "        # model-probability update",
        "        self.mu=cbar*L; self.mu/= self.mu.sum() if self.mu.sum()>0 else 1",
        "        # output combination",
        "        x=sum(self.mu[j]*self.f[j].x for j in range(r))",
        "        P=sum(self.mu[j]*(self.f[j].P+(self.f[j].x-x)@(self.f[j].x-x).T) for j in range(r))",
        "        return x.ravel(), P, self.mu.copy()",
        "print('IMM defined.')",
    ),
    code(
        "# IMM with two NCV models: quiet (small sigma_a) and maneuvering (large sigma_a)",
        "f_quiet=KF(*ncv(T,0.3), sw**2, [meas[0],0], np.diag([sw**2,100.]))",
        "f_maneu=KF(*ncv(T,12.0),sw**2, [meas[0],0], np.diag([sw**2,100.]))",
        "Pi=[[0.97,0.03],[0.10,0.90]]   # transition matrix between modes",
        "imm=IMM([f_quiet,f_maneu], Pi, [0.9,0.1])",
        "",
        "est_imm=[]; mu_hist=[]",
        "for z in meas:",
        "    x,P,mu=imm.step(z); est_imm.append(x[0]); mu_hist.append(mu)",
        "est_imm=np.array(est_imm); mu_hist=np.array(mu_hist)",
        "print(f'IMM overall RMSE={np.sqrt(np.mean((est_imm-pos)**2)):.2f} m,'",
        "      f' maneuver={np.sqrt(np.mean((est_imm[40:60]-pos[40:60])**2)):.2f} m')",
    ),
    code(
        "fig,ax=plt.subplots(2,1,figsize=(11,7),sharex=True)",
        "ax[0].plot(t,np.abs(est_ncv_lo-pos),label='NCV sigma_a=0.5 (error)')",
        "ax[0].plot(t,np.abs(est_nca-pos),label='NCA sigma_a=8')",
        "ax[0].plot(t,np.abs(est_imm-pos),'k',lw=2,label='IMM')",
        "ax[0].axvspan(40,60,color='orange',alpha=.15,label='maneuver')",
        "ax[0].set_ylabel('|position error| [m]'); ax[0].legend(); ax[0].grid(alpha=.3)",
        "ax[0].set_title('IMM combines the strengths: smooth in quiet motion, responsive in a maneuver')",
        "ax[1].plot(t,mu_hist[:,0],label='mu quiet model')",
        "ax[1].plot(t,mu_hist[:,1],label='mu maneuvering model')",
        "ax[1].axvspan(40,60,color='orange',alpha=.15)",
        "ax[1].set_xlabel('t [s]'); ax[1].set_ylabel('model probability'); ax[1].legend(); ax[1].grid(alpha=.3)",
        "ax[1].set_title('IMM model probabilities — the maneuver model \"lights up\" in 40-60s')",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## C. Multiple sensors: is *more data* always better?",
        "Blair presents an experiment (\"Does More Data Always Mean Better...?\"): during a maneuver, **more measurements ",
        "with an inappropriate process-noise variance can hurt**. However, *\"more data does lead to better estimates ",
        "when the fusion is under the correct hypothesis (i.e. maneuvering)\"* — hence IMM, which increases the uncertainty ",
        "during a maneuver, is the key to using extra data correctly.",
    ),
    code(
        "# comparison: single sensor (1 Hz) vs two netted sensors (2 Hz) with IMM",
        "def simulate_imm(meas_t, meas_z, dt):",
        "    fq=KF(*ncv(dt,0.3),sw**2,[meas_z[0],0],np.diag([sw**2,100.]))",
        "    fm=KF(*ncv(dt,12.0),sw**2,[meas_z[0],0],np.diag([sw**2,100.]))",
        "    im=IMM([fq,fm],Pi,[0.9,0.1]); out=[]",
        "    for z in meas_z: x,_,_=im.step(z); out.append(x[0])",
        "    return np.array(out)",
        "",
        "# 2 Hz: double sampling (emulates a second netted sensor)",
        "t2=np.arange(0,N,0.5); idx=np.minimum((t2/T).astype(int),N-1)",
        "meas2=pos[idx]+sw*rng.standard_normal(t2.size)",
        "est2=simulate_imm(t2,meas2,0.5)",
        "# downsample back to 1 Hz for comparison",
        "est2_at1=est2[::2][:N]",
        "print(f'IMM 1 Hz  maneuver RMSE = {np.sqrt(np.mean((est_imm[40:60]-pos[40:60])**2)):.2f} m')",
        "print(f'IMM 2 Hz  maneuver RMSE = {np.sqrt(np.mean((est2_at1[40:60]-pos[40:60])**2)):.2f} m')",
        "print('-> with the correct model (IMM), more data does improve the estimate in the maneuver.')",
    ),
    md(
        "## D. The Extended Kalman Filter (EKF) for nonlinear measurements",
        "Real measurements (radar) are **range and bearing**, $z=h(x)+w$ with nonlinear $h$. The EKF linearizes around the estimate:",
        "",
        "$$\\hat{x}_{k|k}=\\hat{x}_{k|k-1}+K_k[z_k-h(\\hat{x}_{k|k-1})],\\quad K_k=P_{k|k-1}H_k^TS_k^{-1},\\quad H_k=\\left.\\frac{\\partial h}{\\partial x}\\right|_{\\hat{x}_{k|k-1}}$$",
        "",
        "where $H_k$ is the **Jacobian** of $h$. We demonstrate 2-D tracking from range+bearing measurements taken by a sensor at the origin.",
    ),
    code(
        "# EKF: state [x, vx, y, vy], measurement = [range, bearing]",
        "dt=1.0; M=60",
        "Fb=np.array([[1,dt,0,0],[0,1,0,0],[0,0,1,dt],[0,0,0,1.]])",
        "q=0.05",
        "Qb=q*np.array([[dt**3/3,dt**2/2,0,0],[dt**2/2,dt,0,0],",
        "               [0,0,dt**3/3,dt**2/2],[0,0,dt**2/2,dt]])",
        "Rb=np.diag([8.0**2, np.deg2rad(1.5)**2])   # range [m] and bearing [rad] variances",
        "",
        "def h(x):",
        "    r=np.hypot(x[0],x[2]); b=np.arctan2(x[2],x[0]); return np.array([r,b])",
        "def Hjac(x):",
        "    px,py=x[0],x[2]; r2=px**2+py**2; r=np.sqrt(r2)",
        "    return np.array([[px/r,0,py/r,0],[-py/r2,0,px/r2,0]])",
        "",
        "# ground-truth trajectory",
        "xt=np.array([200.,5.,100.,8.]); truth=[]; zs=[]",
        "for _ in range(M):",
        "    xt=Fb@xt; truth.append(xt.copy())",
        "    z=h(xt)+np.array([8.0*rng.standard_normal(), np.deg2rad(1.5)*rng.standard_normal()])",
        "    zs.append(z)",
        "truth=np.array(truth); zs=np.array(zs)",
        "",
        "# EKF",
        "x=np.array([180.,0.,120.,0.]); P=np.diag([100,50,100,50.]); est=[]",
        "for z in zs:",
        "    x=Fb@x; P=Fb@P@Fb.T+Qb                       # predict",
        "    H=Hjac(x); S=H@P@H.T+Rb; K=P@H.T@np.linalg.inv(S)",
        "    y=z-h(x); y[1]=(y[1]+np.pi)%(2*np.pi)-np.pi    # bearing wrap",
        "    x=x+K@y; P=(np.eye(4)-K@H)@P                    # update",
        "    est.append(x.copy())",
        "est=np.array(est)",
        "",
        "# raw measurements in Cartesian coordinates",
        "mx=zs[:,0]*np.cos(zs[:,1]); my=zs[:,0]*np.sin(zs[:,1])",
        "plt.figure(figsize=(7,6))",
        "plt.plot(truth[:,0],truth[:,2],'g',lw=2,label='true trajectory')",
        "plt.plot(mx,my,'.',alpha=.4,label='measurements (range/bearing)')",
        "plt.plot(est[:,0],est[:,2],'r',lw=2,label='EKF estimate')",
        "plt.plot(0,0,'k^',ms=12,label='sensor'); plt.gca().set_aspect('equal')",
        "plt.xlabel('x [m]'); plt.ylabel('y [m]'); plt.legend(); plt.grid(alpha=.3)",
        "plt.title('EKF — tracking from nonlinear range+bearing measurements'); plt.tight_layout(); plt.show()",
        "print(f'EKF position RMSE = {np.sqrt(np.mean((est[:,0]-truth[:,0])**2+(est[:,2]-truth[:,2])**2)):.2f} m')",
    ),
    md(
        "## Summary",
        "* **NCV vs NCA:** no single model is optimal — small $\\sigma_a$ is good in quiet motion and poor in a maneuver, and vice versa.",
        "* **IMM** runs models in parallel and blends them by model probability; achieves 'the best of both worlds' and automatically increases uncertainty during a maneuver.",
        "* *More data* helps **only under the correct hypothesis/model** — the motivation for IMM and for sensible $Q$ tuning.",
        "* **EKF** handles nonlinear measurements (range/bearing) via linearization with the Jacobian $H_k$.",
        "",
        "This concludes the series covering the two decks in the PDF (Blasch — introduction, Blair — estimation). ",
        "Lectures 3–7 (data association, distributed tracking, classification, distributed inference, high-level fusion) ",
        "continue directly from the foundations here — see notebook 00 for the mapping.",
    ),
]

if __name__ == "__main__":
    write_notebook("04_target_tracking_maneuvering.ipynb", cells)
